finished 7 homework
Ninikopaliani/Homework_withbrunch pull request #7
Opened 2024-03-16 19:26 UTC by Ninikopaliani

2024-03-21 21:26 UTC, mishka245 requested changes
დავალება კარგია დავტოვე კომენტარები

2024-03-21 21:26 UTC, mishka245 commented on Homewor_7/Task_1.py
> +    while b < n:
აქ გაქვთ შეცდომა, 

მიმდევრობის წევრი ნომრით 6 არის 8, თქვენი პროგრამა კი არ ბეჭდავს მას 

<img width="298" alt="image" src="https://github.com/Ninikopaliani/Homework_withbrunch/assets/16196685/b02500c5-b7d2-4541-8ea7-8017ce0ded3d">

2024-03-21 21:26 UTC, mishka245 commented on Homewor_7/Task_2.py
> +    i -= 1
ეს ვფიქრობ არ არის საჭირო

2024-03-21 21:26 UTC, mishka245 commented on Homewor_7/Task_2.py
> +        continue
continue while ის ბოლო ხაზზე არ არის საჭირო, აქედან ისედაც ციკლი თავში გადადის პროგრამა

2024-03-21 21:26 UTC, mishka245 commented on Homewor_7/Task_2.py
> +
პროგრამა გამართულად მუშაობს

2024-03-21 21:26 UTC, mishka245 commented on Homewor_7/Task_3.py
> +        continue
continue არ არის საჭირო აქ

2024-04-14 17:38 UTC, merged

2024-06-03 19:51 UTC, khetsurianimariami commented on Homewor_7/Task_1.py
> +    while b < n:
b <= n უკვე ზუსტად დათვლის, სხვა ყველაფერი სწორია.

2024-06-03 19:51 UTC, khetsurianimariami commented on Homewor_7/Task_2.py
პროგრამა გამართულად მუშაობს, ერთადერთი ამ გადმოსახედიდან(უკვე გავლილი კურსიდან) დავამატებდი იმას რომ რამდენიმე ხაზის ამოღება შეგვიძლია და ერთ ხაზში ჩაწერა.

2024-06-03 19:51 UTC, khetsurianimariami commented on Homewor_7/Task_3.py
ძალიან კარგი კოდია, საკმაოდ მოკლედაა ჩაწერილი, პირადად მე ბევრი ვიწვალე ამ დავალებაზე მახოსვს. ერთადერთი ქვედა ტირით თუ არ დავარქმევთ ცვლადს სახელს უმჯობესი იქნებაო. 
P.S. ახლა რომ ვაკეთებდე ამ დავალებას გავასტრინგებდი და ისე ვიპოვიდი შებრუნებულს.